### ISSUE TITLE
AppleReceiptParserService is internal

### ISSUE THREAD

**Issue by oden3d** [shoshins/apple-receipt#15]
Defined as
apple-receipt/Apple.Receipt.Parser/Services/AppleReceiptParserService.cs
`internal class AppleReceiptParserService : IAppleReceiptParserService`
So class AppleReceiptParserService can not be used from other library.

**Comment by jamsoft** [comment]
Yeah, I respect the adherance to good practice but this library is next to impossible to unit test as a result.

**Comment by oden3d** [comment]
I see, but any simple way to run AppleReceiptParserService as part of Nuget package in Console Application for example?

**Comment by jamsoft** [comment]
That wouldn't work when the unit tests are part a suite that runs against your solution in DevOps.

Besides, that would be a test harness, not build process integrated unit testing which is the goal.

**Comment by oden3d** [comment]
I mean someone may want to run receipt validation in their console/desktop app, not unit tests or Web service.

**Comment by shoshins** [comment]
Hi, @DenOsipov, @jamsoft! 

> So class AppleReceiptParserService can not be used from other library.

Yes, that's correct. I follow IoC / DI patterns. I believe that you don't need to think about library implementation, about Unit tests coverage or anything. You simply use library as a service with generic interfaces without any thoughts about details.

I'm sure you know what I'm talking about, but you may go deeper using different kinds of sources such as:
- https://docs.microsoft.com/en-us/dotnet/core/extensions/dependency-injection-usage
- https://medium.com/@amitkma/understanding-inversion-of-control-ioc-principle-163b1dc97454
- etc.

> but this library is next to impossible to unit test as a result.

You don't need to think about tests on your end. All required placed are covered by Internal Unit/Integrated Tests.

>  but any simple way to run AppleReceiptParserService as part of Nuget package in Console Application for example?

Yes, we have simple way to do this. I'm going to upload example.

Thanks for your comments, let me know if some questions remain.
