### ISSUE TITLE
Cannot Get Anything to Work

### ISSUE THREAD

**Issue by jamsoft** [shoshins/apple-receipt#16]
Hi,

I've just started running some tests using this library and unfortunately, none of it seems to work.

I've run this in Startup.cs

'''
var verificationType = Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT") == "Production" ?
    AppleReceiptVerificationType.Production : AppleReceiptVerificationType.Sandbox;

var appleStoreKey = Configuration.GetValue<string>("AppSettings:AppleSharedSecret");

services.RegisterAppleReceiptVerificator(x =>
{
    x.VerifyReceiptSharedSecret = appleStoreKey; // Apple Shared Secret Key
    x.VerificationType = verificationType; // Verification Type: Sandbox / Production
    x.AllowedBundleIds = new[] {"myBundleId"}; // Array with allowed bundle ids
});
'''

When I resolve the service and execute:

```
byte[] data = Convert.FromBase64String(model.PurchaseToken);
AppleAppReceipt receipt = _receiptParserService.GetAppleReceiptFromBytes(data);
```

Receipt is always null.

```
var verificationResult = await _appleReceiptVerificatorService.VerifyAppleReceiptAsync(model.PurchaseToken).ConfigureAwait(false);

var r = await _appleReceiptVerificatorService.VerifyAppleSandBoxReceiptAsync(model.PurchaseToken).ConfigureAwait(false);
```

None of these work either as a result, I guess, of the parser problem.

Unfortunately, I'm now on a crazy deadline so will be removing this library as I just cannot wait for any resolution.

I guess there is some gaps in the documentation or setup.

**Comment by shoshins** [comment]
Hi, @jamsoft! First of all, thanks for your attention to the library. 

> Receipt is always null.

When Apple's server-side verification is failed, you won't be able to see the Receipt itself. You can review an error in that case and decide what to do to fix that. You can also send it here and I will help you to find the answer.

As an example, authentication error:
<img width="905" alt="image" src="https://user-images.githubusercontent.com/5468795/126867618-b7bf525e-316a-4526-885b-6422c8b47704.png">

So, to get Recept you have two options:
1. Continue to use the Verificator library and check the reason for the failure.
2. Simply use the Parser library without verification layer, like that:

```
string receiptData;
var data = Convert.FromBase64String(receiptData);
var receipt = _receiptParserService.GetAppleReceiptFromBytes(data);
```
 
Btw, I'm going to commit extra examples of Verificator / Parser usage.
