### ISSUE TITLE
Refit version conflict

### ISSUE THREAD

**Issue by iam-black** [shoshins/apple-receipt#20]
Hello. Is this library still supported? I am getting an exception while trying to use this library along with a newer Refit version(6+) that is being used in my project. The problem occurs on resolving IAppleReceiptVerificatorService. Downgrade of Refit fixes the issue but it is not desirable in my case. Are there any plans to upgrade packages in your project? Thanks.

> System.InvalidOperationException: IRestService doesn't look like a Refit interface. Make sure it has at least one method with a Refit HTTP method attribute and Refit is installed in the project.

![image](https://user-images.githubusercontent.com/8601553/193921972-57834a72-96e8-41a0-9154-e0f23d3d2621.png)

**Comment by ShawInnes** [comment]
Hi @shoshins - thanks for the quick turnaround on this fix.  I just cloned the repo to test it out and there are a few issues resulting from the change to using System.Text.Json in Refit 6: https://github.com/reactiveui/refit#breaking-changes-in-6x

I've started to create a PR to fix these but just wanted to give you the heads up in case you were planning to release the above PR.

There are two options as I see it:
1. Reference Refit.Newtonsoft.Json and modify `AppleReceiptVerificatorExtensions.cs`

Eg.
```csharp
            services.AddRefitClient<IProductionRestService>(new RefitSettings
                {
                    ContentSerializer = new NewtonsoftJsonContentSerializer()
                })
                .ConfigureHttpClient((serviceProvider, httpClient) 
                    => httpClient.BaseAddress = new Uri(appleProductionUrl));
```
2. Add `[JsonPropertyName(...)]` attributes to all models so they can be serialised using System.Text.Json.  I had a quick look at this option but there are some further challenges with the fact that System.Text.Json doesn't deserialise strings to bools by default.

**Comment by shoshins** [comment]
Thanks @ShawInnes for noticing that. Could you please check if looks good now?

**Comment by ShawInnes** [comment]
> Thanks @ShawInnes for noticing that. Could you please check if looks good now?

Looks good now. I did a test in my solution and it seems to be handling the Json Serialisation correctly now. :)

**Comment by shoshins** [comment]
Ok, great! Unit Tests are fine as well. Should be fine, sending it to Nuget.org. Thanks @ShawInnes and @iam-black for supporting the library 🦾
