### ISSUE TITLE
Making interfaces and classes public to be able to register them in a different DI-Container

### ISSUE THREAD

**Issue by Cotspheer** [shoshins/apple-receipt#27]
I'm using Autofac for wiring up my IoC / DI-Container. As all the interfaces and classes do have the access modifier "internal" I'm not able to register them using the ContainerBuilder from Autofac. Any chance to get thad adjusted?

Thank you in advance for your time!

```c#
using Apple.Receipt.Parser.Services;
using Autofac;

namespace SubscriptionMicroservice.Application.IoC;

public class AppleReceiptParserModule : Module
{
    protected override void Load(ContainerBuilder builder)
    {
        builder.Register<IAppleAsn1NodesParser, AppleAsn1NodesParser>().InstancePerLifetimeScope();
        builder.Register<IAsn1NodesParser, Asn1NodesParser>().InstancePerLifetimeScope();
        builder.Register<IAsn1ParserUtilitiesService, Asn1ParserUtilitiesService>().InstancePerLifetimeScope();
        builder.Register<IAppleReceiptParserService, AppleReceiptParserService>().InstancePerLifetimeScope();

    }
}
```

**Comment by shoshins** [comment]
Hello, @Cotspheer ! 

Have you tried to use the Registration module? We assumed that you need only Parser / Verification interfaces, you don't need to think about / register implementation. 

`services.RegisterAppleReceiptParser();`

You can find an example in Apple.Receipt.Example project.

<img width="759" alt="image" src="https://github.com/shoshins/apple-receipt/assets/5468795/1617613f-8bec-4eab-961b-62dc58d2768f">

<img width="852" alt="image" src="https://github.com/shoshins/apple-receipt/assets/5468795/623329d0-a0d6-41b9-bd03-bfea49bfbb1e">

Let me know if it helps.

**Comment by shoshins** [comment]
Hello, @Cotspheer! Have you had a chance to check if it helps?

**Comment by shoshins** [comment]
Closed for now. Let me know if there is something else I could help with. Thanks.
