### ISSUE TITLE
InvalidOperationException on resolving IOptionsSnapshot<AppleReceiptVerificationSettings> dependency

### ISSUE THREAD

**Issue by petepry** [shoshins/apple-receipt#3]
hello @shoshins and @trejjam
First of all thank you for creating these packages, I do appreciate your work and it being well crafted.

### On to the issue:

**My Setup**:
**OS**: MacOS 10.14.6
**.NET Core SDK version**: 3.1.302
**Package**: Apple.Receipt.Verificator version 2.0.2

`Apple.Receipt.Verificator.Modules.AppleReceiptVerificatorExtension` LOC 26:

```                    
var options = serviceProvider.GetRequiredService<IOptionsSnapshot<AppleReceiptVerificationSettings>>();
```

 throws:

```
System.InvalidOperationException: Cannot resolve scoped service 'Microsoft.Extensions.Options.IOptionsSnapshot`1[Apple.Receipt.Verificator.Models.AppleReceiptVerificationSettings]' from root provider.
```

When resolving injected `IAppleReceiptVerificatorService` in a ASP.NET Core Api Controller (for example).

### Steps to reproduce:

create new web api project:

``` sh
dotnet new webapi -n "webapiappletest"
```

add the package

``` sh
cd webapiappletest/
dotnet add package Apple.Receipt.Verificator --version 2.0.2
```

add in `Startup.cs` in `ConfigureServices`:

``` csharp
            services.RegisterAppleReceiptVerificator(options =>
            {
                options.VerifyReceiptSharedSecret = "xxx";
                options.VerificationType = AppleReceiptVerificationType.Sandbox;
                options.AllowedBundleIds = new[] { "com.example.app" };
            });
```

inject  `IAppleReceiptVerificatorService` in `WeatherForecastController`:

``` csharp
        private readonly ILogger<WeatherForecastController> _logger;
        private readonly IAppleReceiptVerificatorService _appleVerificationService;

        public WeatherForecastController(ILogger<WeatherForecastController> logger, IAppleReceiptVerificatorService appleVerificationService)
        {
            _logger = logger;
            _appleVerificationService = appleVerificationService;
        }
```

open in browser:
http://localhost:5000/weatherforecast

result:
throws exception

``` csharp
System.InvalidOperationException: Cannot resolve scoped service 'Microsoft.Extensions.Options.IOptionsSnapshot`1[Apple.Receipt.Verificator.Models.AppleReceiptVerificationSettings]' from root provider.
```

expected result:
Does not throw exception ;)

### Possible reason for an exception:
Using `IOptionsSnapshot` which is a **scoped** service while configuring a **singleton** http client `Refit` in `Apple.Receipt.Verificator.Modules.AppleReceiptVerificatorExtension`:

``` csharp
        public static IServiceCollection RegisterAppleReceiptVerificator(this IServiceCollection services, Action<AppleReceiptVerificationSettings>? configureOptions = null)
        {
            services.RegisterAppleReceiptParser();

            if (configureOptions != null)
            {
                services.Configure<AppleReceiptVerificationSettings>(configureOptions);
            }

            services.AddRefitClient<IRestService>()
                .ConfigureHttpClient((serviceProvider, httpClient) =>
                {
                    var options = serviceProvider.GetRequiredService<IOptionsSnapshot<AppleReceiptVerificationSettings>>();

                    httpClient.BaseAddress = new Uri(options.Value.VerifyUrl);
                });

            services.TryAddScoped<IAppleReceiptVerificatorService, AppleReceiptVerificatorService>();

            return services;
        }
```

When swapping `IOptionsSnapshot` with either `IOptions` or `IOptionsMonitor` **the exception does not occur**. Official docs on `IOptions...`: [link](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-3.1#options-interfaces)

**Another thing** is the `app.config` file mentions `Autofac` dependency but it doesn't do anything in the .NET Core environment, I guess. Seems like a leftover from .NET Framework.

### Possible fix
1. Using `IOptions` or `IOptionsMonitor` with its consequences (refer to docs: [link](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-3.1#options-interfaces))
2. Creating a local scope and getting the `IOptionsSnapshot` from the scope:

``` csharp
            services.AddRefitClient<IRestService>()
                .ConfigureHttpClient((serviceProvider, httpClient) =>
                {
                    using (var scope = serviceProvider.CreateScope())
                    {
                        var options = scope.ServiceProvider.GetRequiredService<IOptionsSnapshot<AppleReceiptVerificationSettings>>();
                        httpClient.BaseAddress = new Uri(options.Value.VerifyUrl);
                    }
                });
```
3. (my personal preferred) Using [IHttpClientFactory](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests) instead of external dependency *Refit* (if I understand correctly) and moving the logic deciding which Apple Receipt Verify Url (Prod or Sandbox) to use into the Verifying logic itself either by getting it from the already injected `IOptionsSnapshot<AppleReceiptVerificationSettings>` in the `Apple.Receipt.Verificator.Services.AppleReceiptVerificatorService` or passing it even down from `AppleReceiptVerificatorService.VerifyAppleReceiptAsync(string receiptData)` something like `AppleReceiptVerificatorService.VerifyAppleReceiptAsync(AppleReceiptVerificationType verificationType, string receiptData)` down to the HttpClient instance.
That way we get rid of `Refit` dependency and are more flexible about where to send the receipt data (like when Apple Server responds with wrong environment status and we gotta resend it to the correct one, which btw the package does not allow in its current state).

Let me know what you think and if you accept PRs.
Cheers!

**Comment by trejjam** [comment]
Hi, firstly I am not a maintainer (so I am not in charge here :) ).

> Using IOptionsSnapshot which is a scoped service while configuring a singleton http client Refit

Why do you think HttpClient is singleton? HttpClient configured using `AddRefitClient` -> `AddHttpClient` is transient (it is not in container, but HttpClientFactory creates new with each call of `IHttpClientFactory.Create`)

> (my personal preferred) Using IHttpClientFactory instead of external dependency Refit

Refit is generated RestClient (from an interface) which uses HttpClient internally.

Are you sure you have opened scope while resolving dependency for `WeatherForecastController`? I am not aware of singleton dependencies.

**Comment by trejjam** [comment]
>I am not in charge here :)

I prefer `IOptions` as a simple solution.

I do not mix testing and production env. Therefore I do not need to change an endpoint after an app starts. But if you need it, you will need to replace Refit and implement a REST client.

**Comment by petepry** [comment]
> Hi, firstly I am not a maintainer (so I am not in charge here :) ).

Oh, sorry to bother you then, I've noticed some commits by you and thought you are the maintainer as well ;)

> Why do you think HttpClient is singleton? HttpClient configured using `AddRefitClient` -> `AddHttpClient` is transient (it is not in container, but HttpClientFactory creates new with each call of `IHttpClientFactory.Create`)

My bad, you are right, I've seen a `services.AddSingleton(provider => RequestBuilder.ForType<T>(settings));` line in `public static IHttpClientBuilder AddRefitClient` and made an assumption this is about HttpClient but now I'm guessing it's rather about `RequestBuilder settings` which, I assume, is used by Refit/HttpClient. Then I don't know why the exception is thrown.

> Refit is generated RestClient (from an interface) which uses HttpClient internally.

You are right :)

> Are you sure you have opened scope while resolving dependency for `WeatherForecastController`? I am not aware of singleton dependencies.

I'm not sure if I get it right, I am injecting `IAppleReceiptVerificatorService` dependency into `WeatherForecastController` through the constructor of the controller, do you mean I should explicitly create a scope and resolve the `IAppleReceiptVerificatorService` from it instead?
`IAppleReceiptVerificatorService` is being registered as scoped in `RegisterAppleReceiptVerificator` method so it should be available in the `WeatherForecastController` but the exception is thrown inside the `RegisterAppleReceiptVerificator` method when

``` csharp
 var options = serviceProvider.GetRequiredService<IOptionsSnapshot<AppleReceiptVerificationSettings>>();
```

is being executed. If I create a scope for it like:

``` csharp
 using (var scope = serviceProvider.CreateScope())
{
    var options = scope.ServiceProvider.GetRequiredService<IOptionsSnapshot<AppleReceiptVerificationSettings>>();
    httpClient.BaseAddress = new Uri(options.Value.VerifyUrl);
}
```

then it does not throw an exception but the original code without creation of the scope is the internal package code. This part doesn't allow me to use the package "as is" because of the exception.
Do you guys have an example project where it "just works" or can point me to such?


>I do not mix testing and production env. Therefore I do not need to change an endpoint after an app starts. But if you need it, you will need to replace Refit and implement a REST client.

I was under the impression that there may be a case when a production app is under AppStore review and Apple tester may want to test newly introduced in app but do so on the sandbox env while connected to prod server thus when the apple server returns the specific status saying "wrong environment" we may want to fallback and check the receipt again using different env. I've seen similar solution in a python package where the author explains it here: [https://itunes-iap.readthedocs.io/en/latest/quick.html#apple-in-review-mode](https://itunes-iap.readthedocs.io/en/latest/quick.html#apple-in-review-mode). But that may not be viable for all scenarios.

**Comment by trejjam** [comment]
> Oh, sorry to bother you then

No problem

> Do you guys have an example project where it "just works" or can point me to such?

I am using DryIoc instead of default ServiceProvider. That's why I overlooked unresolved service (it works slightly different), that is not an excuse for bug :)

> when a production app is under AppStore review and Apple tester

That makes sense

Will you make a PR?

**Comment by petepry** [comment]
> I am using DryIoc instead of default ServiceProvider. That's why I overlooked unresolved service (it works slightly different), that is not an excuse for bug :)

Ah, that explains why am I experiencing the exception. I am using out of the box DI/IoC solution provided by the .NET Core framework in that case (clean, fresh project) which definitely works differently in some cases. 
As I mentioned before, I've noticed a reference to Autofac package in the app.config file of the `Apple.Receipt.Verificator` package which doesn't do anything in my case but if I were using Autofac it may have worked.
Still, there is no mention of Autofac or different IoC requirement for the Verificator package to work thus I've assumed it works out of the box.

> Will you make a PR?

I may craft some later but are you referring to PR fixing the exception I'm experiencing or the "dual env/review mode" of the Apple receipt verification logic?
I'm still not sure which way to go with fixing the exception (changing the IOptions type or restructuring how the HttpClient is produced/configured/used). I would add the "review mode" when changing how HttpClient is used though.

**Comment by trejjam** [comment]
> I've noticed a reference to Autofac package in the app.config

It should work with any DI. Autofac was the only possibility before packages conversion to .Net Core. Now, it's no longer important.

> when a production app is under AppStore review and Apple tester

This sounds like a must-have feature, which requires dual mode. What do you think @shoshins?

**Comment by shoshins** [comment]
Hi, @petepry, @trejjam. 

**First of all, thank you guys for your attention to the library.** 

As for the exception, the question is not actual anymore, am I right? I can check with the latest web project template (just to be sure), but I believe DI should work there as usual.

> This sounds like a must-have feature, which requires dual mode. What do you think @shoshins?

Sounds like that. I've not heard about that before but looks like a great feature. I'll read about that. 

> I may craft some later but are you referring to PR fixing the exception I'm experiencing or the "dual env/review mode" of the Apple receipt verification logic?

It would be great if you were able to make some code suggestions in PR. I'll try to do it by myself, but it may take time.

P.S. Sorry for the long delay.

**Comment by trejjam** [comment]
> the question is not actual anymore

It is, the library works with DryIoc, but not with .NetCore default IoC

The question is how the fix should look like.

One option is to only fix the registration replacing `IOptionsSnapshot` with `IOptions`. Which solves the issue, but.

The second option is to change library internals and change how the library works with variable (sandbox/production) and Apple custom response code telling the library to choose a different endpoint. I think this is a better option.

**Comment by shoshins** [comment]
@trejjam @petepry Hi, guys! I've checked your point. 

> One option is to only fix the registration replacing IOptionsSnapshot with IOptions. Which solves the issue, but.

And selected this fix as the easiest one. + I've written a Web API example with an Integration test.

Could you check it in the "bugfix/#3-IOption-resolver-crash" branch, please? If it works for you, I'll merge it in a week. It looks fine as for me.

As for "The second option", will review it later.
