### ISSUE TITLE
AppleReceiptVerificationResult.Status is obsolete however is used for error codes instead of AppleVerificationResponse 

### ISSUE THREAD

**Issue by kolesnick** [shoshins/apple-receipt#8]
AppleReceiptVerificationResult.Status is marked as obsolete.
However if something goes wrong it is populated with data leaving AppleVerificationResponse property equal to null.

I propose it not to be obsolete or change error handling behaviour.

**Comment by shoshins** [comment]
Hi, @kolesnick . Thanks for the comment.

> I propose it not to be obsolete or change error handling behaviour.

Yes, agree. Status marked back as an actual field.
